# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb-service
# spec:
#   selector:
#     app: mongodb-single
#   clusterIP: None
#   ports:
#   - name: "27017"
#     port: 27017
#     targetPort: 27017


apiVersion: v1
kind: Service
metadata:
  name: mongodb-single
  labels:
    app: mongodb
spec:
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
  selector:
    app: mongodb