apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-single
  labels:
    app: mongodb
spec:
  serviceName: mongodb-single
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      # serviceAccountName: mongodb-single
      securityContext:
        fsGroup: 1001
        sysctls: []
      containers:
        - name: mongodb
          image: mongo:4.4.5
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          # utilizando secretos de kubernetes
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
          ports:
            - name: mongodb
              containerPort: 27017
          resources:
            requests:
              memory: 300Mi
              cpu: 250m
            limits:
              memory: 500Mi
              cpu: 500m
          volumeMounts:
            - name: data-mongodb
              mountPath: /data/db
      # volumes:
      #   - name: data-mongodb
      #     persistentVolumeClaim:
      #       claimName: mongodb-pv
  volumeClaimTemplates:
    - metadata:
        name: data-mongodb
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "500Mi"