# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongodb-pv
# spec:
#   capacity:
#     storage: 200Mi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: local-mongo
#   local:
#     path: /data/db
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - testing-worker
# ---
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: local-mongo
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer