apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.5
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            # utilizando secretos de kubernetes
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
          resources:
            limits:
              memory: "200Mi"
              cpu: "250m"
          securityContext:
            allowPrivilegeEscalation: false
#          volumeMounts:
#              - name: mongodb-pvc
#                mountPath: /data/db
#      volumes:
#        - name: mongodb-pvc
#          persistentVolumeClaim:
#            claimName: mongodb-pvc
