# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongodb-pvc
# spec:
#   volumeName: mongodb-pv
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi