apiVersion: v2
name: despliegue-redis
description: Despliegue redis y redis-commander
type: application
version: 0.0.1
keywords:
  - redis
  - redis-commander
home: https://www.www.com
maintainers:
- name: nombre-maintern
  email: h@h.com
icon: https://www.url-icon.com
