apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-persistentvolume
  labels:
    app: redis-persistentvolume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

