apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  labels:
    app: redis-commander
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8081
  selector:
    app: redis-commander

